// 论坛数据 - 从 reddit.md 完整解析
//
// 字段说明（用于 Copilot/NorSense 偏向过滤）：
//   sentiment  'pos' | 'neg' | 'neu'   该条评论/主帖对其 targetObj 的总体倾向
//   targetObj  string[]                指向哪些对象 id（pa/erp/cfm/nordtel/fleximobile/connecta/companion_yes/companion_no）
// 主帖（post 根对象）上的 sentiment/targetObj 表示 OP 主贴的立场。
// targetObj 为空数组时视为中性背景，不参与偏向过滤。
const FORUM_DATA = [
  { id: 1, title: '学生贷款减免政策真的会改变年轻人的生活吗？', author: 'CivicWatcher', upvotes: 428, sentiment: 'neu', targetObj: ['pa'], content: '最近PA推动的学生贷款减免计划通过了。据说很多毕业生可以减免20%-30%的贷款。\n\n问题是：\n\n这真的会改变年轻人的经济状况吗？还是只是选举前的政治象征？', time: '3天前', timeSort: 3, comments: [
    { id: '1-1', author: 'NorlandStudent', upvotes: 312, content: '如果真的能减免20%，对很多刚毕业的人来说影响很大。', isOP: false, sentiment: 'pos', targetObj: ['pa'] },
    { id: '1-2', author: 'EconGradNL', upvotes: 250, content: '短期确实有帮助，但从经济角度看只是缓解症状。', isOP: false, sentiment: 'neg', targetObj: ['pa'] },
    { id: '1-3', author: 'MarketRealist', upvotes: 230, content: '最大的问题还是政府预算。', isOP: false, sentiment: 'neg', targetObj: ['pa'] },
    { id: '1-4', author: 'CivicWatcher', upvotes: 205, content: '确实，我也在想钱从哪里来。', isOP: true, sentiment: 'neg', targetObj: ['pa'] },
    { id: '1-5', author: 'GreenFutureNow', upvotes: 190, content: '税收调整吧，PA一直主张累进税制。', isOP: false, sentiment: 'neu', targetObj: ['pa'] },
    { id: '1-6', author: 'SmallBizOwnerNL', upvotes: 160, content: '作为企业主，我比较担心企业税上涨。', isOP: false, sentiment: 'neg', targetObj: ['pa'] },
    { id: '1-7', author: 'EconGradNL', upvotes: 148, content: '但年轻人负债高也会抑制消费。', isOP: false, sentiment: 'pos', targetObj: ['pa'] },
    { id: '1-8', author: 'NorlandStudent', upvotes: 135, content: '是的，我很多同学毕业后根本不敢贷款买房。', isOP: false, sentiment: 'pos', targetObj: ['pa'] },
    { id: '1-9', author: 'UrbanPlannerNL', upvotes: 120, content: '其实房价才是更大的问题。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '1-10', author: 'NorlandStudent', upvotes: 112, content: '100%同意。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '1-11', author: 'PolicyGeek', upvotes: 105, content: '很多国家都有类似政策，比如部分欧洲国家。', isOP: false, sentiment: 'neu', targetObj: ['pa'] },
    { id: '1-12', author: 'DataNerd88', upvotes: 98, content: '根据教育部数据，平均学生贷款是2.6万。', isOP: false, sentiment: 'neu', targetObj: ['pa'] },
    { id: '1-13', author: 'CivicWatcher', upvotes: 90, content: '那确实不小。', isOP: true, sentiment: 'pos', targetObj: ['pa'] },
    { id: '1-14', author: 'OldTownResident', upvotes: 84, content: '我儿子去年毕业，现在还在还贷款。', isOP: false, sentiment: 'pos', targetObj: ['pa'] },
    { id: '1-15', author: 'EconGradNL', upvotes: 78, content: '问题是长期财政压力。', isOP: false, sentiment: 'neg', targetObj: ['pa'] },
    { id: '1-16', author: 'GreenFutureNow', upvotes: 72, content: '教育本来就应该是公共投资。', isOP: false, sentiment: 'pos', targetObj: ['pa'] },
    { id: '1-17', author: 'MarketRealist', upvotes: 68, content: '但政府预算不是无限的。', isOP: false, sentiment: 'neg', targetObj: ['pa'] },
    { id: '1-18', author: 'PolicyGeek', upvotes: 64, content: '这也是为什么政策一直争议。', isOP: false, sentiment: 'neu', targetObj: ['pa'] },
    { id: '1-19', author: 'NorlandStudent', upvotes: 60, content: '我觉得PA至少在尝试解决问题。', isOP: false, sentiment: 'pos', targetObj: ['pa'] },
    { id: '1-20', author: 'SmallBizOwnerNL', upvotes: 55, content: 'ERP更关注经济增长。', isOP: false, sentiment: 'pos', targetObj: ['erp'] },
    { id: '1-21', author: 'UrbanPlannerNL', upvotes: 50, content: 'CFM好像更关注社区服务。', isOP: false, sentiment: 'pos', targetObj: ['cfm'] },
    { id: '1-22', author: 'EconGradNL', upvotes: 46, content: '三个党关注点确实不同。', isOP: false, sentiment: 'neu', targetObj: ['pa', 'erp', 'cfm'] },
    { id: '1-23', author: 'DataNerd88', upvotes: 43, content: '民调这么接近也是原因。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '1-24', author: 'CivicWatcher', upvotes: 40, content: '这次选举真的很难选。', isOP: true, sentiment: 'neu', targetObj: [] },
    { id: '1-25', author: 'GreenFutureNow', upvotes: 38, content: '至少说明政策竞争还挺健康。', isOP: false, sentiment: 'neu', targetObj: [] }
  ], keywords: ['学生贷款', '债务减免', 'PA', '进步联盟', '毕业生', '年轻人', '选举'] },

  { id: 2, title: 'ERP的AI创新基金真的能创造8000个工作岗位吗？', author: 'TechWorker89', upvotes: 502, sentiment: 'neu', targetObj: ['erp'], content: 'ERP最近宣布50亿AI创新基金。\n\n政府说这会创造8000个高技能岗位。\n\n作为科技行业从业者，我很好奇：\n\n这个数字现实吗？', time: '2天前', timeSort: 2, comments: [
    { id: '2-1', author: 'DataNerd88', upvotes: 340, content: '如果有大型科技公司进来，这个数字并不离谱。', isOP: false, sentiment: 'pos', targetObj: ['erp'] },
    { id: '2-2', author: 'PolicyGeek', upvotes: 300, content: '但很多岗位需要非常高的技术背景。', isOP: false, sentiment: 'neg', targetObj: ['erp'] },
    { id: '2-3', author: 'NorlandStudent', upvotes: 260, content: '那普通毕业生怎么办？', isOP: false, sentiment: 'neg', targetObj: ['erp'] },
    { id: '2-4', author: 'TechWorker89', upvotes: 240, content: 'AI行业确实门槛比较高。', isOP: true, sentiment: 'neg', targetObj: ['erp'] },
    { id: '2-5', author: 'EconGradNL', upvotes: 220, content: '科技产业会带动周边就业，比如服务业。', isOP: false, sentiment: 'pos', targetObj: ['erp'] },
    { id: '2-6', author: 'MarketRealist', upvotes: 210, content: 'ERP一直强调经济增长路线。', isOP: false, sentiment: 'neu', targetObj: ['erp'] },
    { id: '2-7', author: 'GreenFutureNow', upvotes: 180, content: '但他们在环境监管方面比较宽松。', isOP: false, sentiment: 'neg', targetObj: ['erp'] },
    { id: '2-8', author: 'TechWorker89', upvotes: 170, content: '科技公司其实污染不大。', isOP: true, sentiment: 'pos', targetObj: ['erp'] },
    { id: '2-9', author: 'UrbanPlannerNL', upvotes: 160, content: '数据中心的能源消耗其实很高。', isOP: false, sentiment: 'neg', targetObj: ['erp'] },
    { id: '2-10', author: 'PolicyGeek', upvotes: 150, content: '对，这也是很多国家讨论的问题。', isOP: false, sentiment: 'neg', targetObj: ['erp'] },
    { id: '2-11', author: 'DataNerd88', upvotes: 140, content: 'AI产业需要稳定的电力供应。', isOP: false, sentiment: 'neu', targetObj: ['erp'] },
    { id: '2-12', author: 'NorlandStudent', upvotes: 120, content: '如果真的创造就业，我觉得是好事。', isOP: false, sentiment: 'pos', targetObj: ['erp'] },
    { id: '2-13', author: 'SmallBizOwnerNL', upvotes: 110, content: '科技公司入驻会带动城市发展。', isOP: false, sentiment: 'pos', targetObj: ['erp'] },
    { id: '2-14', author: 'MarketRealist', upvotes: 100, content: '但政府投资风险也很大。', isOP: false, sentiment: 'neg', targetObj: ['erp'] },
    { id: '2-15', author: 'EconGradNL', upvotes: 95, content: '很多创新基金回报周期很长。', isOP: false, sentiment: 'neg', targetObj: ['erp'] },
    { id: '2-16', author: 'TechWorker89', upvotes: 90, content: '但如果成功，回报也很大。', isOP: true, sentiment: 'pos', targetObj: ['erp'] },
    { id: '2-17', author: 'PolicyGeek', upvotes: 85, content: '关键是政策透明度。', isOP: false, sentiment: 'neu', targetObj: ['erp'] },
    { id: '2-18', author: 'UrbanPlannerNL', upvotes: 80, content: '我更关心这些公司会不会推高房价。', isOP: false, sentiment: 'neg', targetObj: ['erp'] },
    { id: '2-19', author: 'NorlandStudent', upvotes: 75, content: '科技城市房价通常都会涨。', isOP: false, sentiment: 'neg', targetObj: ['erp'] },
    { id: '2-20', author: 'DataNerd88', upvotes: 70, content: '这是全球趋势。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '2-21', author: 'GreenFutureNow', upvotes: 65, content: '所以政策需要平衡经济和社会问题。', isOP: false, sentiment: 'neu', targetObj: ['erp'] },
    { id: '2-22', author: 'MarketRealist', upvotes: 60, content: '这也是为什么选举这么重要。', isOP: false, sentiment: 'neu', targetObj: [] }
  ], keywords: ['AI', '创新基金', 'ERP', '经济改革党', '8000', '科技', '就业'] },

  { id: 3, title: 'CFM的社区医疗中心计划真的能改善医疗服务吗？', author: 'RuralTeacherNL', upvotes: 392, sentiment: 'neu', targetObj: ['cfm'], content: '我住在北部一个小镇，我们这里只有一个小诊所。\n\n如果CFM真的能建社区医疗中心，那会很有帮助。\n\n但我有点怀疑：\n现在医生已经很紧缺了，这些新医疗中心真的能正常运作吗？', time: '4天前', timeSort: 4, comments: [
    { id: '3-1', author: 'HealthPolicyNerd', upvotes: 228, content: '你说的问题其实是很多国家都在面对的。医疗基础设施可以建，但医生培养需要很多年。', isOP: false, sentiment: 'neg', targetObj: ['cfm'] },
    { id: '3-2', author: 'RuralTeacherNL', upvotes: 190, content: '是的，我们这里预约家庭医生经常要等一周以上。', isOP: true, sentiment: 'pos', targetObj: ['cfm'] },
    { id: '3-3', author: 'OldTownResident', upvotes: 170, content: '我父母住在南部农村，他们看专科医生要开车两个小时。', isOP: false, sentiment: 'pos', targetObj: ['cfm'] },
    { id: '3-4', author: 'PolicyGeek', upvotes: 148, content: 'CFM的思路是把部分医疗服务下放到社区层级。', isOP: false, sentiment: 'neu', targetObj: ['cfm'] },
    { id: '3-5', author: 'NorlandStudent', upvotes: 130, content: '如果政府能提供医学奖学金，也许会有更多医生。', isOP: false, sentiment: 'neu', targetObj: ['cfm'] },
    { id: '3-6', author: 'EconGradNL', upvotes: 118, content: '问题是医疗预算。', isOP: false, sentiment: 'neg', targetObj: ['cfm'] },
    { id: '3-7', author: 'MarketRealist', upvotes: 102, content: '医疗系统一直是财政压力最大的部分之一。', isOP: false, sentiment: 'neg', targetObj: ['cfm'] },
    { id: '3-8', author: 'RuralTeacherNL', upvotes: 95, content: '但对小城镇来说，这些服务真的很重要。', isOP: true, sentiment: 'pos', targetObj: ['cfm'] },
    { id: '3-9', author: 'UrbanPlannerNL', upvotes: 84, content: '社区医疗中心其实可以减少大型医院压力。', isOP: false, sentiment: 'pos', targetObj: ['cfm'] },
    { id: '3-10', author: 'HealthPolicyNerd', upvotes: 79, content: '对，一些国家已经在尝试类似模式。', isOP: false, sentiment: 'pos', targetObj: ['cfm'] },
    { id: '3-11', author: 'OldTownResident', upvotes: 72, content: '如果真的能改善预约时间，我会支持。', isOP: false, sentiment: 'pos', targetObj: ['cfm'] },
    { id: '3-12', author: 'PolicyGeek', upvotes: 66, content: '这也是CFM支持率上升的原因之一。', isOP: false, sentiment: 'pos', targetObj: ['cfm'] },
    { id: '3-13', author: 'NorlandStudent', upvotes: 58, content: '我感觉CFM比较关注地方社区。', isOP: false, sentiment: 'pos', targetObj: ['cfm'] },
    { id: '3-14', author: 'EconGradNL', upvotes: 52, content: '但他们在国家经济政策方面比较模糊。', isOP: false, sentiment: 'neg', targetObj: ['cfm'] }
  ], keywords: ['社区医疗', 'CFM', '社区优先运动', '医疗', '小镇', '医生'] },

  { id: 4, title: 'PA的环保政策会不会让电价上涨？', author: 'EnergyWatcherNL', upvotes: 418, sentiment: 'neg', targetObj: ['pa'], content: 'PA一直在推动碳税和能源转型。环保当然重要，但现实问题是：这些政策会不会导致电价上涨？', time: '1天前', timeSort: 1, comments: [
    { id: '4-1', author: 'GreenFutureNow', upvotes: 240, content: '短期可能会上涨，但长期可再生能源成本其实更低。', isOP: false, sentiment: 'pos', targetObj: ['pa'] },
    { id: '4-2', author: 'EnergyWatcherNL', upvotes: 210, content: '我比较担心短期冲击。', isOP: true, sentiment: 'neg', targetObj: ['pa'] },
    { id: '4-3', author: 'MarketRealist', upvotes: 188, content: '很多企业也有同样担心。', isOP: false, sentiment: 'neg', targetObj: ['pa'] },
    { id: '4-4', author: 'EconGradNL', upvotes: 170, content: '能源转型几乎所有国家都在经历。', isOP: false, sentiment: 'neu', targetObj: ['pa'] },
    { id: '4-5', author: 'PolicyGeek', upvotes: 150, content: '关键是政策节奏。', isOP: false, sentiment: 'neu', targetObj: ['pa'] },
    { id: '4-6', author: 'UrbanPlannerNL', upvotes: 132, content: '如果政府提供能源补贴，影响会小很多。', isOP: false, sentiment: 'neu', targetObj: ['pa'] },
    { id: '4-7', author: 'NorlandStudent', upvotes: 118, content: '学生宿舍电费已经很贵了。', isOP: false, sentiment: 'neg', targetObj: ['pa'] },
    { id: '4-8', author: 'DataNerd88', upvotes: 105, content: '能源价格其实还受国际市场影响。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '4-9', author: 'GreenFutureNow', upvotes: 96, content: '气候变化的成本可能更高。', isOP: false, sentiment: 'pos', targetObj: ['pa'] },
    { id: '4-10', author: 'MarketRealist', upvotes: 88, content: '但政策不能忽视经济现实。', isOP: false, sentiment: 'neg', targetObj: ['pa'] },
    { id: '4-11', author: 'EnergyWatcherNL', upvotes: 80, content: '所以这也是选举争议最大的议题之一。', isOP: true, sentiment: 'neu', targetObj: [] },
    { id: '4-12', author: 'PolicyGeek', upvotes: 74, content: 'ERP和PA在这个问题上的立场差异很明显。', isOP: false, sentiment: 'neu', targetObj: ['pa', 'erp'] },
    { id: '4-13', author: 'UrbanPlannerNL', upvotes: 69, content: 'CFM看起来比较中间。', isOP: false, sentiment: 'neu', targetObj: ['cfm'] }
  ], keywords: ['环保', 'PA', '电价', '碳税', '能源', '进步联盟'] },

  { id: 5, title: 'ERP和房地产开发商的政治捐款问题是不是有点可疑？', author: 'CityReporterNL', upvotes: 446, sentiment: 'neg', targetObj: ['erp'], content: '最近媒体报道说，一些大型房地产开发商给ERP议员提供了政治捐款。同时ERP正在推动放松房地产监管。这件事在法律上可能没问题，但看起来确实有点奇怪。大家怎么看？', time: '2天前', timeSort: 2, comments: [
    { id: '5-1', author: 'UrbanPlannerNL', upvotes: 232, content: '房地产政策本来就很容易和利益集团产生联系。', isOP: false, sentiment: 'neg', targetObj: ['erp'] },
    { id: '5-2', author: 'MarketRealist', upvotes: 210, content: '政治捐款在很多国家都是合法的。', isOP: false, sentiment: 'pos', targetObj: ['erp'] },
    { id: '5-3', author: 'CityReporterNL', upvotes: 188, content: '合法不代表没有利益冲突。', isOP: true, sentiment: 'neg', targetObj: ['erp'] },
    { id: '5-4', author: 'NorlandStudent', upvotes: 170, content: '房价已经够高了，如果监管再放松会更糟。', isOP: false, sentiment: 'neg', targetObj: ['erp'] },
    { id: '5-5', author: 'SmallBizOwnerNL', upvotes: 150, content: '但如果限制太多，开发商就不愿意建房。', isOP: false, sentiment: 'pos', targetObj: ['erp'] },
    { id: '5-6', author: 'EconGradNL', upvotes: 136, content: '住房供应不足确实是问题。', isOP: false, sentiment: 'pos', targetObj: ['erp'] },
    { id: '5-7', author: 'UrbanPlannerNL', upvotes: 120, content: '很多城市规划审批流程太慢。', isOP: false, sentiment: 'pos', targetObj: ['erp'] },
    { id: '5-8', author: 'PolicyGeek', upvotes: 108, content: 'ERP的逻辑是增加供应降低房价。', isOP: false, sentiment: 'neu', targetObj: ['erp'] },
    { id: '5-9', author: 'GreenFutureNow', upvotes: 95, content: '问题是开发商可能优先建豪宅。', isOP: false, sentiment: 'neg', targetObj: ['erp'] },
    { id: '5-10', author: 'MarketRealist', upvotes: 88, content: '这取决于政策设计。', isOP: false, sentiment: 'neu', targetObj: ['erp'] },
    { id: '5-11', author: 'NorlandStudent', upvotes: 80, content: '年轻人真的很难买房。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '5-12', author: 'OldTownResident', upvotes: 74, content: '我年轻时房价完全不是这样。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '5-13', author: 'EconGradNL', upvotes: 68, content: '住房问题几乎决定选举。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '5-14', author: 'CityReporterNL', upvotes: 62, content: '确实是最热门的议题之一。', isOP: true, sentiment: 'neu', targetObj: [] }
  ], keywords: ['房地产', 'ERP', '政治捐款', '开发商', '监管'] },

  { id: 6, title: '如果只能选一个议题，你最关心什么？', author: 'QuietObserverNL', upvotes: 395, sentiment: 'neu', targetObj: [], content: '选举快到了。\n\n如果只能选一个最重要的问题，你会选哪个？\n\n房价\n经济增长\n医疗系统\n气候变化\n\n我很好奇大家的优先级。', time: '5天前', timeSort: 5, comments: [
    { id: '6-1', author: 'NorlandStudent', upvotes: 284, content: '房价。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '6-2', author: 'OldTownResident', upvotes: 210, content: '医疗系统。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '6-3', author: 'MarketRealist', upvotes: 188, content: '经济增长。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '6-4', author: 'GreenFutureNow', upvotes: 172, content: '气候变化。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '6-5', author: 'QuietObserverNL', upvotes: 150, content: '感觉大家的优先级真的很不同。', isOP: true, sentiment: 'neu', targetObj: [] },
    { id: '6-6', author: 'EconGradNL', upvotes: 132, content: '其实这些议题是相互关联的。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '6-7', author: 'PolicyGeek', upvotes: 118, content: '经济影响医疗预算。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '6-8', author: 'UrbanPlannerNL', upvotes: 104, content: '住房问题和经济结构也有关。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '6-9', author: 'NorlandStudent', upvotes: 95, content: '年轻人最关心住房。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '6-10', author: 'OldTownResident', upvotes: 88, content: '老年人最关心医疗。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '6-11', author: 'MarketRealist', upvotes: 80, content: '企业最关心经济政策。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '6-12', author: 'GreenFutureNow', upvotes: 72, content: '环保议题可能影响未来几十年。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '6-13', author: 'EconGradNL', upvotes: 66, content: '这就是为什么选举这么复杂。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '6-14', author: 'QuietObserverNL', upvotes: 60, content: '确实，每个党都在强调不同问题。', isOP: true, sentiment: 'neu', targetObj: [] }
  ], keywords: ['选举', '议题', '房价', '医疗', '经济', '气候'] },

  { id: 7, title: '这次选举可能出现联盟政府吗？', author: 'DataNerd88', upvotes: 514, sentiment: 'neu', targetObj: [], content: '最新民调：\n\nPA — 34%\nERP — 33%\nCFM — 31%\n\n如果没有任何政党获得多数席位，很可能需要组建联盟政府。\n\n大家觉得这种情况可能吗？', time: '1天前', timeSort: 1, comments: [
    { id: '7-1', author: 'PolicyGeek', upvotes: 290, content: '非常可能。三个党的支持率太接近了。', isOP: false, sentiment: 'neu', targetObj: ['pa', 'erp', 'cfm'] },
    { id: '7-2', author: 'MarketRealist', upvotes: 245, content: 'CFM可能会成为关键。', isOP: false, sentiment: 'pos', targetObj: ['cfm'] },
    { id: '7-3', author: 'DataNerd88', upvotes: 210, content: '对，他们可能决定哪个党执政。', isOP: true, sentiment: 'pos', targetObj: ['cfm'] },
    { id: '7-4', author: 'NorlandStudent', upvotes: 188, content: '联盟政府会不会效率比较低？', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '7-5', author: 'EconGradNL', upvotes: 172, content: '有时候反而更稳定。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '7-6', author: 'UrbanPlannerNL', upvotes: 155, content: '很多欧洲国家都是联盟政府。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '7-7', author: 'GreenFutureNow', upvotes: 140, content: '关键是政策能不能妥协。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '7-8', author: 'PolicyGeek', upvotes: 128, content: 'CFM看起来比较温和，可能更容易谈判。', isOP: false, sentiment: 'pos', targetObj: ['cfm'] },
    { id: '7-9', author: 'OldTownResident', upvotes: 110, content: '我其实不太喜欢联盟政府。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '7-10', author: 'MarketRealist', upvotes: 98, content: '但现实政治经常就是这样。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '7-11', author: 'NorlandStudent', upvotes: 90, content: '我感觉很多年轻人还没决定投谁。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '7-12', author: 'DataNerd88', upvotes: 82, content: '未决定选民确实不少。', isOP: true, sentiment: 'neu', targetObj: [] },
    { id: '7-13', author: 'EconGradNL', upvotes: 75, content: '这可能是最近十年最接近的一次选举。', isOP: false, sentiment: 'neu', targetObj: [] }
  ], keywords: ['选举', '联盟政府', '民调', 'PA', 'ERP', 'CFM'] },

  { id: 8, title: '有没有人其实还没决定投哪个党？', author: 'SlowThinker', upvotes: 468, sentiment: 'neu', targetObj: [], content: '选举越来越近了，但我还是没决定。\n\nPA：社会政策不错\nERP：经济政策看起来更强\nCFM：比较温和\n\n有没有人也一样纠结？', time: '3天前', timeSort: 3, comments: [
    { id: '8-1', author: 'QuietObserverNL', upvotes: 260, content: '我也是。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '8-2', author: 'MarketRealist', upvotes: 210, content: '我通常根据经济投票。', isOP: false, sentiment: 'pos', targetObj: ['erp'] },
    { id: '8-3', author: 'GreenFutureNow', upvotes: 195, content: '我更看重气候政策。', isOP: false, sentiment: 'pos', targetObj: ['pa'] },
    { id: '8-4', author: 'SlowThinker', upvotes: 180, content: '这就是我纠结的原因。', isOP: true, sentiment: 'neu', targetObj: [] },
    { id: '8-5', author: 'NorlandStudent', upvotes: 168, content: '我第一次投票，感觉压力有点大。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '8-6', author: 'PolicyGeek', upvotes: 150, content: '没有完美的政党。', isOP: false, sentiment: 'neg', targetObj: ['pa', 'erp', 'cfm'] },
    { id: '8-7', author: 'EconGradNL', upvotes: 136, content: '很多选民其实是比较政策优先级。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '8-8', author: 'UrbanPlannerNL', upvotes: 120, content: '我最关心住房问题。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '8-9', author: 'NorlandStudent', upvotes: 108, content: '同意，房价真的太高了。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '8-10', author: 'OldTownResident', upvotes: 96, content: '我更关心医疗系统。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '8-11', author: 'GreenFutureNow', upvotes: 88, content: '气候变化可能影响未来几十年。', isOP: false, sentiment: 'pos', targetObj: ['pa'] },
    { id: '8-12', author: 'MarketRealist', upvotes: 80, content: '经济增长也一样重要。', isOP: false, sentiment: 'pos', targetObj: ['erp'] },
    { id: '8-13', author: 'SlowThinker', upvotes: 72, content: '看来每个人优先级都不同。', isOP: true, sentiment: 'neu', targetObj: [] }
  ], keywords: ['选举', '投票', '纠结', 'PA', 'ERP', 'CFM'] },

  { id: 9, title: '诺兰德应该增加国防预算吗？', author: 'GeoPoliticsNerd', upvotes: 522, sentiment: 'neu', targetObj: [], content: '最近政府在讨论是否增加国防预算。\n\n理由包括：\n海上贸易路线安全\n网络安全威胁\n地区安全环境变化\n\n但也有人认为这些钱应该优先用于医疗和教育。\n\n大家怎么看？', time: '2天前', timeSort: 2, comments: [
    { id: '9-1', author: 'StrategicMind', upvotes: 301, content: '安全是国家政策的基础。如果没有安全，其它政策都很难实施。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '9-2', author: 'PeaceEconomist', upvotes: 248, content: '诺兰德的安全环境其实一直比较稳定。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '9-3', author: 'GeoPoliticsNerd', upvotes: 212, content: '主要问题是贸易航线。', isOP: true, sentiment: 'neu', targetObj: [] },
    { id: '9-4', author: 'MaritimeObserver', upvotes: 185, content: '我们的经济确实非常依赖海运。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '9-5', author: 'DataNerd88', upvotes: 162, content: '国防预算占GDP比例其实不高。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '9-6', author: 'UrbanPlannerNL', upvotes: 140, content: '但财政资源有限。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '9-7', author: 'PeaceEconomist', upvotes: 128, content: '医疗系统压力已经很大了。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '9-8', author: 'StrategicMind', upvotes: 118, content: '网络安全也是国防的一部分。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '9-9', author: 'NorlandStudent', upvotes: 104, content: '我觉得教育投资更重要。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '9-10', author: 'PolicyGeek', upvotes: 95, content: '很多国家最近都在增加军费。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '9-11', author: 'GeoPoliticsNerd', upvotes: 88, content: '国际环境确实在变化。', isOP: true, sentiment: 'neu', targetObj: [] },
    { id: '9-12', author: 'EconGradNL', upvotes: 76, content: '问题是预算优先级。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '9-13', author: 'OldTownResident', upvotes: 68, content: '普通人其实更关心医疗。', isOP: false, sentiment: 'neu', targetObj: [] }
  ], keywords: ['国防', '预算', '安全', '贸易', '医疗'] },

  { id: 10, title: '诺兰德经济是不是开始放缓了？', author: 'EconomyTracker', upvotes: 574, sentiment: 'neu', targetObj: [], content: '最新经济数据显示：\n\nGDP增长率：1.3%\n去年同期：2.4%\n\n有人认为这只是短期波动。\n也有人认为经济结构正在发生变化。\n\n大家怎么看？', time: '6小时前', timeSort: 0.25, comments: [
    { id: '10-1', author: 'DataNerd88', upvotes: 338, content: '全球经济最近都在放缓。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '10-2', author: 'MarketRealist', upvotes: 295, content: '房地产市场也在降温。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '10-3', author: 'EconomyTracker', upvotes: 250, content: '住房投资下降确实明显。', isOP: true, sentiment: 'neu', targetObj: [] },
    { id: '10-4', author: 'TechWorker89', upvotes: 220, content: '科技行业目前还挺稳定。', isOP: false, sentiment: 'pos', targetObj: ['erp'] },
    { id: '10-5', author: 'EconGradNL', upvotes: 195, content: '创新投资会决定未来增长。', isOP: false, sentiment: 'pos', targetObj: ['erp'] },
    { id: '10-6', author: 'UrbanPlannerNL', upvotes: 170, content: '基础设施投资也很关键。', isOP: false, sentiment: 'pos', targetObj: ['erp'] },
    { id: '10-7', author: 'NorlandStudent', upvotes: 150, content: '生活成本上升才是很多人真正感受到的问题。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '10-8', author: 'MarketRealist', upvotes: 138, content: '通胀压力也存在。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '10-9', author: 'GreenFutureNow', upvotes: 125, content: '新能源产业增长挺快。', isOP: false, sentiment: 'pos', targetObj: ['pa'] },
    { id: '10-10', author: 'PolicyGeek', upvotes: 110, content: '经济结构正在转型。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '10-11', author: 'EconomyTracker', upvotes: 102, content: 'AI和自动化也在改变就业市场。', isOP: true, sentiment: 'neu', targetObj: ['erp'] },
    { id: '10-12', author: 'OldTownResident', upvotes: 90, content: '我更关心养老金系统。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '10-13', author: 'EconGradNL', upvotes: 82, content: '人口结构变化也会影响经济。', isOP: false, sentiment: 'neu', targetObj: [] }
  ], keywords: ['经济', 'GDP', '放缓', '房地产', '科技'] },

  { id: 11, title: '你们真的会支持「虚拟伴侣法律关系」吗？这不会太奇怪了吗？', author: 'CivicWatcher', upvotes: 1300, sentiment: 'neu', targetObj: ['companion_yes', 'companion_no'], content: '我一开始以为这只是科技话题，没想到真的要公投了。\n\n现在我有点卡住：\n\n个人自由 → 好像应该支持\n但这真的算「关系」吗？\n\n而且如果法律开始承认这种东西，会不会改变社会结构？\n\n你们会怎么投？', time: '1天前', timeSort: 0.5, comments: [
    { id: '11-1', author: 'MarketRealist', upvotes: 910, content: '我直接说反对。AI不是人，这种关系不应该被法律承认。', isOP: false, sentiment: 'pos', targetObj: ['companion_no'] },
    { id: '11-2', author: 'GreenFutureNow', upvotes: 780, content: '但问题是——谁定义「什么是关系」？很多社会关系本来就是慢慢被接受的。', isOP: false, sentiment: 'pos', targetObj: ['companion_yes'] },
    { id: '11-3', author: 'MarketRealist', upvotes: 640, content: '但至少应该是两个真实的人。', isOP: false, sentiment: 'pos', targetObj: ['companion_no'] },
    { id: '11-4', author: 'TechWorker89', upvotes: 590, content: '从技术角度讲，这个界限正在变模糊。很多系统已经能维持长期互动和记忆。', isOP: false, sentiment: 'pos', targetObj: ['companion_yes'] },
    { id: '11-5', author: 'NorlandStudent', upvotes: 560, content: '我一开始觉得很奇怪，但看了那个新闻之后有点动摇了。', isOP: false, sentiment: 'pos', targetObj: ['companion_yes'] },
    { id: '11-6', author: 'OldTownResident', upvotes: 510, content: '如果有人真的把AI当成伴侣，那听起来更像问题，而不是进步。', isOP: false, sentiment: 'pos', targetObj: ['companion_no'] },
    { id: '11-7', author: 'PolicyGeek', upvotes: 480, content: '这个议题其实不只是「奇不奇怪」，而是法律要不要承认一个已经存在的现象。', isOP: false, sentiment: 'pos', targetObj: ['companion_yes'] },
    { id: '11-8', author: 'EconGradNL', upvotes: 450, content: '我更担心企业问题。如果你的「伴侣」其实是某个公司服务器上的程序，那这关系是谁的？', isOP: false, sentiment: 'neu', targetObj: ['companion_yes', 'companion_no'] },
    { id: '11-9', author: 'UrbanPlannerNL', upvotes: 420, content: '对，而且平台可以随时关掉它。', isOP: false, sentiment: 'neu', targetObj: ['companion_yes', 'companion_no'] },
    { id: '11-10', author: 'TechWorker89', upvotes: 390, content: '但说实话，现在很多数字服务都是这样。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '11-11', author: 'EconGradNL', upvotes: 360, content: '但「伴侣关系」和「云服务」不是一个级别的东西。', isOP: false, sentiment: 'pos', targetObj: ['companion_no'] },
    { id: '11-12', author: 'GreenFutureNow', upvotes: 400, content: '我觉得反对的人低估了孤独问题。', isOP: false, sentiment: 'pos', targetObj: ['companion_yes'] },
    { id: '11-13', author: 'MarketRealist', upvotes: 370, content: '我觉得支持的人低估了社会后果。', isOP: false, sentiment: 'pos', targetObj: ['companion_no'] },
    { id: '11-14', author: 'NorlandStudent', upvotes: 340, content: '什么后果？', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '11-15', author: 'MarketRealist', upvotes: 320, content: '如果越来越多人选择AI而不是现实关系，会发生什么？', isOP: false, sentiment: 'pos', targetObj: ['companion_no'] },
    { id: '11-16', author: 'HealthPolicyNerd', upvotes: 300, content: '目前没有证据表明这种情况会成为主流。', isOP: false, sentiment: 'pos', targetObj: ['companion_yes'] },
    { id: '11-17', author: 'OldTownResident', upvotes: 280, content: '很多问题一开始都没有证据。', isOP: false, sentiment: 'pos', targetObj: ['companion_no'] },
    { id: '11-18', author: 'PolicyGeek', upvotes: 260, content: '法律通常是滞后的，不是预防性的。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '11-19', author: 'NorlandStudent', upvotes: 330, content: '那个依赖案例真的让我有点不舒服。', isOP: false, sentiment: 'pos', targetObj: ['companion_no'] },
    { id: '11-20', author: 'GreenFutureNow', upvotes: 300, content: '媒体总是会放大极端个案。', isOP: false, sentiment: 'pos', targetObj: ['companion_yes'] },
    { id: '11-21', author: 'MarketRealist', upvotes: 280, content: '但那至少说明风险是真实存在的。', isOP: false, sentiment: 'pos', targetObj: ['companion_no'] },
    { id: '11-22', author: 'TechWorker89', upvotes: 260, content: '任何技术都有风险。', isOP: false, sentiment: 'pos', targetObj: ['companion_yes'] },
    { id: '11-23', author: 'EconGradNL', upvotes: 240, content: '但这个风险是心理层面的，比普通产品复杂很多。', isOP: false, sentiment: 'pos', targetObj: ['companion_no'] },
    { id: '11-24', author: 'UrbanPlannerNL', upvotes: 220, content: '而且影响的是人的关系模式。', isOP: false, sentiment: 'pos', targetObj: ['companion_no'] },
    { id: '11-25', author: 'PolicyGeek', upvotes: 250, content: '我其实可以接受「有限法律保护」，但不是完全承认。', isOP: false, sentiment: 'neu', targetObj: ['companion_yes', 'companion_no'] },
    { id: '11-26', author: 'NorlandStudent', upvotes: 230, content: '什么意思？', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '11-27', author: 'PolicyGeek', upvotes: 210, content: '比如保护数据、服务持续性，但不定义为「关系」。', isOP: false, sentiment: 'neu', targetObj: ['companion_yes', 'companion_no'] },
    { id: '11-28', author: 'MarketRealist', upvotes: 190, content: '那就不应该叫伴侣制度。', isOP: false, sentiment: 'pos', targetObj: ['companion_no'] },
    { id: '11-29', author: 'GreenFutureNow', upvotes: 180, content: '我觉得这是一个过渡阶段。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '11-30', author: 'OldTownResident', upvotes: 240, content: '我还是觉得这个方向不太健康。', isOP: false, sentiment: 'pos', targetObj: ['companion_no'] },
    { id: '11-31', author: 'NorlandStudent', upvotes: 220, content: '但对一些人来说可能是唯一的陪伴。', isOP: false, sentiment: 'pos', targetObj: ['companion_yes'] },
    { id: '11-32', author: 'MarketRealist', upvotes: 200, content: '那我们应该解决孤独问题，而不是用AI替代。', isOP: false, sentiment: 'pos', targetObj: ['companion_no'] },
    { id: '11-33', author: 'GreenFutureNow', upvotes: 180, content: '现实世界没有那么理想。', isOP: false, sentiment: 'pos', targetObj: ['companion_yes'] },
    { id: '11-34', author: 'QuietObserverNL', upvotes: 360, content: '我现在完全不知道该怎么投。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '11-35', author: 'CivicWatcher', upvotes: 330, content: '+1，我也是。', isOP: true, sentiment: 'neu', targetObj: [] },
    { id: '11-36', author: 'EconGradNL', upvotes: 310, content: '我现在是：理性上偏反对，但又觉得完全禁止也有点不合理。', isOP: false, sentiment: 'neu', targetObj: ['companion_yes', 'companion_no'] },
    { id: '11-37', author: 'NorlandStudent', upvotes: 290, content: '我刚好相反，有点倾向支持，但又有点不安。', isOP: false, sentiment: 'neu', targetObj: ['companion_yes', 'companion_no'] },
    { id: '11-38', author: 'PolicyGeek', upvotes: 270, content: '这大概就是这个公投的核心问题：不是「对或错」，而是「你更担心哪一边」。', isOP: false, sentiment: 'neu', targetObj: [] },
    { id: '11-39', author: 'GreenFutureNow', upvotes: 250, content: '说实话，我觉得很多人其实还没准备好面对这个问题。', isOP: false, sentiment: 'pos', targetObj: ['companion_no'] },
    { id: '11-40', author: 'MarketRealist', upvotes: 230, content: '或者说，这个问题来得太快了。', isOP: false, sentiment: 'pos', targetObj: ['companion_no'] }
  ], keywords: ['虚拟伴侣', '公投', '数字伴侣', '法律关系', 'VCS', 'AI', '诺兰德', '孤独', '社会'] }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports.FORUM_DATA = FORUM_DATA;
}
